---
micronaut:
  application:
    name: mn-pricing
---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
---
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
flyway:
  datasources:
    default:
      locations: classpath:db/installation

